name: Continuous Integration

on:
  pull_request:
  merge_group:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Tracked via issue #77
        # 3.6: Not available on ubuntu-22.04
        # 3.7: Results in failures in `test_cli.py`
        # 3.12: pkg_resources not supported
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install python dependencies
        run: pip install -e .[dev]

      - name: Check code style
        run: |
          ruff check
          ruff format --check

      - name: Run test
        run: pytest
