name: unit-tests
on:
  pull_request:
  merge_group:
jobs:
  launch-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'
          cache: 'pip'
          cache-dependency-path: setup.py
      - run: python -m venv env
      - run: source env/bin/activate
      - run: env/bin/pip install -e .
      - run: env/bin/pip install pytest
      - run: env/bin/pytest
