name: unit-tests
on:
  pull_request:
  merge_group:
jobs:
  launch-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Tracked via issue #77
        # 3.6: Not available on ubuntu-22.04
        # 3.7: Results in failures in `test_cli.py`
        # 3.12: pkg_resources not supported
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m venv env
      - run: source env/bin/activate
      - run: env/bin/pip install -e .
      - run: env/bin/pip install pytest
      - run: env/bin/pytest
